In [1]:
import numpy

In [4]:
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
%timeit [j**3 for j in range(1,9)]

406 ns ± 9.77 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
import numpy as np
%timeit np.arange(1,9)**4 

1.35 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
import numpy as np
l = []
x = int(input("Enter how many elements you want to enter in array"))
for i in range(1,x+1):
    y = int(input("Enter element : "))
    l.append(y)
z = np.array(l)
print(z)

Enter how many elements you want to enter in array 4
Enter element :  5
Enter element :  3
Enter element :  78
Enter element :  12


[ 5  3 78 12]


In [14]:
import numpy as np
x = np.array([12,5,3,8])
print(x)
print(x.ndim)

[12  5  3  8]
1


In [31]:
import numpy as np
y = np.array([1,4,2],ndmin=10)
print(y)
print(y.ndim)

[[[[[[[[[[1 4 2]]]]]]]]]]
10


# Types of Array

In [36]:
import numpy as  np
x = np.empty(4)
x = np.empty((3,4))
print(x)

[[8.38009223e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.03977794e-312 5.15250723e-062 3.96321673e-061 5.88364369e-062]
 [6.40181958e+170 2.08894364e-076 8.60534131e-067 2.44609108e-056]]


In [40]:
import numpy as  np
x = np.zeros(4)
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
import numpy as np
z = np.ones(4)
print(z)
print()
z = np.ones((5,3))
print(z)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
import numpy as np
u = np.arange(5)
print(u)

[0 1 2 3 4]


In [47]:
import numpy as np
i = np.linspace(1,15,num=3)
print(i)

[ 1.  8. 15.]
