# Day 2 Learning

In [31]:
import numpy as np
x = np.array([2,1,3,1,1,2,3,2,3,21,1,4],ndmin=3)
print(x.ndim)
print(x.shape)
print(x)
print()
var = x.reshape(6,2,1)
print(var)
print(var.ndim)

3
(1, 1, 12)
[[[ 2  1  3  1  1  2  3  2  3 21  1  4]]]

[[[ 2]
  [ 1]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 2]]

 [[ 3]
  [ 2]]

 [[ 3]
  [21]]

 [[ 1]
  [ 4]]]
3


# Indexing and Slicing

In [32]:
import numpy as np # indexing in 1 dimension
x = np.array([2,1,3,1,1,2,3,2,3,21,1,4],ndmin=1)
print(x[9])

21


In [33]:
import numpy as np # indexing in 2 dimension
x = np.array([2,1,3,1,1,2,3,2,3,21,1,4],ndmin=2)
print(x[0,9])

21


In [35]:
import numpy as np # indexing in 3 dimension
x = np.array([2,1,3,1,1,2,3,2,3,21,1,4],ndmin=3)
print(x[0,0,9])

21


In [59]:
import numpy as np # indexing in 3 dimension before and after reshape
x = np.array([[[2,1],[1,1],[2,32],[2,3]]])
print("x shape : ",x.shape)
print(x[0,2,1]) # -> Index change
print("After Reshaping")
x = x.reshape(4,1,2) # -> Index Change
print(x)
print("x shape : ",x.shape)
print(x[2,0,1])

x shape :  (1, 4, 2)
32
After Reshaping
[[[ 2  1]]

 [[ 1  1]]

 [[ 2 32]]

 [[ 2  3]]]
x shape :  (4, 1, 2)
32


In [56]:
import numpy as np # Slicing in 1 dimension
x = np.array([1,3,5,8])
print(x[1:])
print(x[1:3])
print(x[:-1])
print(x[-4:])
print(x[1:3:2])

[3 5 8]
[3 5]
[1 3 5]
[1 3 5 8]
[3]


In [63]:
import numpy as np # slicing in 3 dimension understand carefully
x = np.array([[[2,1],[1,1],[2,32],[2,3]]])
print(x)
print(x[0,2,0:2])

[[[ 2  1]
  [ 1  1]
  [ 2 32]
  [ 2  3]]]
[ 2 32]


In [65]:
import numpy as np # slicing in 3 dimension understand carefully
x = np.array([2,1,1,1,2,32,2,3],ndmin=3)
print(x.shape)
print(x[0,0,4:6])

(1, 1, 8)
[ 2 32]


# Iteration

In [68]:
import numpy as np # Iteration in 2 dimension using for and nditer()
x = np.array([2,1,1,1,2,32,2,3],ndmin=2)
for i in x:
    print(i)
print()
for i in np.nditer(x):
    print(i)

[ 2  1  1  1  2 32  2  3]

2
1
1
1
2
32
2
3


In [83]:
import numpy as np # iteration in 3 dimension using for and nditer
x = np.array([[[2,1],[1,1],[2,32],[2,3]]])
for i in x:
    #for j in i:
        #for k in j:
    print(i,end=" ")
    print()
print()
for i in np.nditer(x):
    print(i)
print()
for i in np.ndenumerate(x): # Use to show the index of corresponding value
    print(i)

[[ 2  1]
 [ 1  1]
 [ 2 32]
 [ 2  3]] 

2
1
1
1
2
32
2
3

((0, 0, 0), 2)
((0, 0, 1), 1)
((0, 1, 0), 1)
((0, 1, 1), 1)
((0, 2, 0), 2)
((0, 2, 1), 32)
((0, 3, 0), 2)
((0, 3, 1), 3)


# Copy vs View

In [86]:
import numpy as np # In copy, the original data is store new array so changing in copy will not affect the original data
x = np.array([1,385,29])
co = x.copy()
print(x)
print(co)
co[0] = 35
x[0] =20
print(x)
print(co)

[  1 385  29]
[  1 385  29]
[ 20 385  29]
[ 35 385  29]


In [88]:
import numpy as np # In view,the data set is same so when changing the data using view variable vi then it will affect the original data
x = np.array([1,385,29])
vi = x.view()
print(x)
print(vi)
vi[0] = 35
print(x)
x[0] =20
print(x)

[  1 385  29]
[  1 385  29]
[ 35 385  29]
[ 20 385  29]


# Join and Split

In [90]:
import numpy as np
x = np.array([1,32,2,1])
y = np.array([10,3,21,11])
k = np.concatenate((x,y))
print(k)

[ 1 32  2  1 10  3 21 11]


In [95]:
import numpy as np
x = np.array([1,21,211,931],ndmin=2)
y = np.array([12,31,1211,9031],ndmin=2)
i = np.concatenate((x,y)) #-> bydefault axis = 0 i.e. column concatenation
j = np.concatenate((x,y),axis=1) #-> axis =1 means row concatenation
print(i)
print()
print(j)

[[   1   21  211  931]
 [  12   31 1211 9031]]

[[   1   21  211  931   12   31 1211 9031]]


In [99]:
import numpy as np
x = np.array([1,21,211,931],ndmin=2)
y = np.array([12,31,1211,9031],ndmin=2)
i = np.stack((x,y)) #-> column
j = np.hstack((x,y)) #-> row
k = np.vstack((x,y)) #-> column

print(i)
print()
print(j)
print(k)
print(i.shape)
print(k.shape)

[[[   1   21  211  931]]

 [[  12   31 1211 9031]]]

[[   1   21  211  931   12   31 1211 9031]]
[[   1   21  211  931]
 [  12   31 1211 9031]]
(2, 1, 4)
(2, 4)


In [104]:
import numpy as np # Splitting of 2 dimension array
x = np.array([[1,21],[211,931]])
y = np.array_split(x,2)
print(y)
print(y[0])
print(type(y))

[array([[ 1, 21]]), array([[211, 931]])]
[[ 1 21]]
<class 'list'>
