# random function

In [2]:
import numpy as np
x = np.random.rand(3,2)
print(x)

[[0.80088915 0.18873575]
 [0.08579815 0.65750377]
 [0.25001807 0.19862194]]


In [5]:
import numpy as np
y = np.random.ranf(3)
print(y)

[0.50692507 0.64128455 0.43232508]


In [6]:
import numpy as np
o = np.random.randn(3,2)
print(o)

[[ 0.78010045  1.84095803]
 [ 0.67152825 -1.08739163]
 [-0.12469899 -0.35394578]]


In [8]:
import numpy as np
w = np.random.randint(3,18,16)
print(w)

[ 5  7 12 13 16  4 15 15 12  5  4 16  5  5 17  7]


In [10]:
import numpy as np
n = np.array(([1,1,4],[2,1,4],[8,2,1]),ndmin=3)
print(n)

[[[1 1 4]
  [2 1 4]
  [8 2 1]]]


# Changing datatypes

In [11]:
import numpy as np ##to check datatype
x = np.array([1,2,3,4])
print("Data type : ",x.dtype)

Data type :  int32


In [13]:
import numpy as np ## 1st type
x = np.array([1,2,3,4],dtype=np.int16)
print("Data type : ",x.dtype)

Data type :  int16


In [16]:
import numpy as np ## 2nd type
x = np.array([1,2,3,4])
new = np.float32(x)
print("Data type : ",x.dtype)
print("Data type ; ",new.dtype)
print(new)
print(x)

Data type :  int32
Data type ;  float32
[1. 2. 3. 4.]
[1 2 3 4]


In [19]:
import numpy as np ### 3rd type
x = np.array([0,2,3,4])
new = x.astype(bool)
print("Data type : ",x.dtype)
print(x)
print(new)

Data type :  int32
[0 2 3 4]
[False  True  True  True]


# Numpy Operations

In [20]:
import numpy as np # normal way
x = np.array([2,4,21,3])
b = x + 4
print(b)

[ 6  8 25  7]


In [23]:
import numpy as np # using function
x = np.array([2,4,21,3])
b = np.array([2,34,21,3])
add = np.add(x,b)
print(add)

[ 4 38 42  6]


In [26]:
import numpy as np # reciprocal
x = np.array([4,2,5,2])
b = np.reciprocal(x.astype(float))
print(b)

[0.25 0.5  0.2  0.5 ]


In [28]:
import numpy as np # using mod
x = np.array([32,2,11,9])
b = np.mod(x,2)
print(b)

[0 0 1 1]


# operation in 2d array

In [30]:
import numpy as np # using mulitply
x = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
y = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
mul = np.multiply(x,y)
print(mul)

[[1024    4  121   81]
 [   4    1   16    4]]


# Arithmetic Operations

In [31]:
import numpy as np # using sqrt
x = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
print(np.sqrt(x))

[[5.65685425 1.41421356 3.31662479 3.        ]
 [1.41421356 1.         2.         1.41421356]]


In [33]:
import numpy as np # using max and min
x = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
print(np.max(x),np.argmax(x)) ## argmax and argmin is used to find the index at which it is located whether it is maximum or minimum
print(np.min(x),np.argmin(x))

32 0
1 5


In [39]:
import numpy as np # using cumsum bydeafault continious addition and if axis =1 then row addittion
x = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
print(np.cumsum(x,axis=1))
print(np.cumsum(x))

[[32 34 45 54]
 [ 2  3  7  9]]
[32 34 45 54 56 57 61 63]


In [37]:
import numpy as np # using cumsum if axis = 0 then column addition
x = np.array(([32,2,11,9],[2,1,4,2]),ndmin=2)
print(np.cumsum(x,axis=0))

[[32  2 11  9]
 [34  3 15 11]]


In [61]:
import numpy as np # no of elements in a array
x = np.array([[123,21,21],[2,1,4]])
print("size of x : ",x.size)

size of x :  6


# Shape and Reshape

In [51]:
import numpy as np # function to check the shape
x = np.array(([23,3,1,9],[3,3,21,1]),ndmin=2)
print(x.ndim)
print(x.shape)
print(x)

2
(2, 4)
[[23  3  1  9]
 [ 3  3 21  1]]


In [58]:
import numpy as np # function to change the shape
x = np.array(([23,3,1,9],[3,3,21,1]),ndmin=2)
print(x.ndim)
print(x.shape)
print()
var = x.reshape(2,2,2)
print(var.ndim)
print(var.shape)
print(var)

2
(2, 4)

3
(2, 2, 2)
[[[23  3]
  [ 1  9]]

 [[ 3  3]
  [21  1]]]


In [60]:
import numpy as np # revise this always to understand better 
x = np.array([2,1,3,1,1,2,3,2,3,21,1,4],ndmin=3)
print("size of array : ",x.size)
print(x.ndim)
print(x.shape)
print(x)
print()
var = x.reshape(6,2,1) # output will be 6 rows further divided into 2 each row will have 1 column (6*2*1) = (number of elements in an array) i.e. 12
print(var)
print(var.ndim)

size of array :  12
3
(1, 1, 12)
[[[ 2  1  3  1  1  2  3  2  3 21  1  4]]]

[[[ 2]
  [ 1]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 2]]

 [[ 3]
  [ 2]]

 [[ 3]
  [21]]

 [[ 1]
  [ 4]]]
3


In [62]:
import numpy as np
x = np.array([[1,2,2],[2,4,3]])
print(x.shape)

(2, 3)
