# Numpy Array Functions

In [4]:
import numpy as np # Searching in a array using Where Function
x = np.array([2,113,31,59])
y = np.where((x%2) == 0)
print(y)
print(type(y))

(array([0], dtype=int64),)
<class 'tuple'>


In [9]:
import numpy as np # Using sort sorting the function
x = np.array([2,113,31,59])
x = np.sort(x)
print(x)
y = np.searchsorted(x,31) # Search sorted is basically tells the index at which,given value will be inserted using binary search
print(y)

[  2  31  59 113]
1


In [10]:
import numpy as np # This whole code represent how to filter the elements to create a array which is desirable. let say in this array I want 2 and 31 in a new array then i will this procedure
x = np.array([2,113,31,59])
f = [True,False,True,False]
var = x[f]
print(var)

[ 2 31]


In [13]:
import numpy as np # Random.shuffle function is used to shuffle the array
x = np.array([2,113,31,59])
np.random.shuffle(x)
print(x)

[ 31   2 113  59]


In [16]:
import numpy as np # Unique function is used to find the unique values from the array 
x = np.array([2,113,31,5,31,2])
y = np.unique(x,return_index=True)# return_index parameter is optional
print(y)

(array([  2,   5,  31, 113]), array([0, 3, 2, 1], dtype=int64))


In [17]:
import numpy as np # Using resize we can change the dimension
x = np.array([2,113,31,59])
y = np.resize(x,(2,2))
print(y)

[[  2 113]
 [ 31  59]]


In [ ]:
import numpy as np # Using sort sorting the function
x = np.array([2,113,31,59])

# Insert and Delete

In [22]:
import numpy as np # Using insert and append,adding elements to the array
x = np.array([2,113,31,59])
x=np.insert(x,3,8)
x = np.append(x,46)
print(x)

[  2 113  31   8  59  46]


In [26]:
import numpy as np # Using insert, adding elements to the array
x = np.array([[2,113],[31,59]])
x = np.insert(x,1,45,axis=0)
print(x)

[[  2 113]
 [ 45  45]
 [ 31  59]]


In [28]:
import numpy as np # Using delete function
x = np.array([2,113,31,59])
x = np.delete(x,2)
print(x)

[  2 113  59]
